### ISSUE TITLE
Imports of Rcpp not needed

### ISSUE THREAD

**Issue by eddelbuettel** [fernote7/ecoseries#3]
Your version 0.1.00 of ecoseries shows an Imports: Rcpp, but your package has no compiled code.

You don't need it.  I just create a test version of the package with the `Imports: Rcpp`, and it passes `R CMD check` just fine -- and in fact with one fewer warning.  The version on CRAN shows

```
N  checking dependencies in R code
   Namespace in Imports field not imported from: ‘Rcpp’
     All declared Imports should be used.
```

already alerting you to this.

**Comment by fernote7** [comment]
You are right. Thank you for the alert, I fixed this in the github repository and will submit a new version to CRAN by the end of the week.

**Comment by eddelbuettel** [comment]
No need to rush the CRAN upload.  If it is fixed in your repo, it will get fixed with the next upload.  I would wait til I had a more substantial change -- it is not really a usage-limiting bug.  Rcpp has to be on the users machines anyway because the package you do import for a reason.
