### ISSUE TITLE
como encontrar a id de uma série do IpeaData?

### ISSUE THREAD

**Issue by lincolnfrias** [fernote7/ecoseries#5]
Olá,

parabéns pelo pacote! Mas não consigo encontrar onde ficam os números identificadores das séries do IpeaData :(

**Comment by fernote7** [comment]
Boa noite,,

Este é um problema do pacote que eu pretendo solucionar já tem um tempo. 

Por enquanto, o melhor jeito (menos pior) é ir no site do ipeadata, selecionar a série que você deseja e ao carregar a página clicar com o botão direito e ir em "inspecionar elemento" (ou Inspect). Deve abrir um menu e de lá se você procurar por "serid". O número que aparece após o símbolo de igual é o número da série que você deseja.
 
Por enquanto é a única forma. 

![ipeadata](https://user-images.githubusercontent.com/6413276/27753841-b68e189e-5dbd-11e7-88b8-0a4e867438e4.jpg)

**Comment by lincolnfrias** [comment]
Ótimo, muito obrigado, @fernote7!
