### ISSUE TITLE
Sidra - period of search

### ISSUE THREAD

**Issue by arthurwelle** [fernote7/ecoseries#6]
Hello, thanks for the nice work you did!
Is it possible **not** to use dates ("to" and "from") when extracting a serie from sidra? The API allows it (as in "/p/all" and "/p/last"), but I didn´t find a way using your package, am I missing something?  
My goal is to dynamically extract series until the last period avaliable (which is variable).
Thank you.

**Comment by fernote7** [comment]
If I remember correctly, you can input today (or this month) as argument and the API understands that you want the last available data points.

On Aug 17, 2017 09:44, arthurwelle <notifications@github.com> wrote:

Hello, thanks for the nice work you did!
Is it possible not to use dates ("to" and "from") when extracting a serie from sidra? The API allows it (as in "/p/all" and "/p/last"), but I didn´t find a way using your package, am I missing something?
My goal is to dynamically extract series until the last period avaliable (which is variable).
Thank you.

**Comment by arthurwelle** [comment]
Perfect! I tried a date earlier than a series earliest date and get an error, but now I see that this is not the case with a date later than the last date. Thanks for the quick reply!
Regards!
