### ISSUE TITLE
Séries do IPEADATa

### ISSUE THREAD

**Issue by analisemacro** [fernote7/ecoseries#7]
Olá, pessoal, tudo bem?

Primeiro, parabéns pelo pacote. Bem legal.

Tentei pegar a série abaixo, porém ela me retornou sem valor

consumo_sa = series_ipeadata(1198638884, periodicity = 'D')

A periodicidade da série é trimestral, mas as opções disponíveis são Y, M e D.

Não sei se é esse o problema, mas...

Alguma dica?

Abs

**Comment by fernote7** [comment]
Obrigado pelo feedback, vou averiguar e consertar o problema.

**Comment by fernote7** [comment]
Problema resolvido. Só baixar de novo pelo CRAN ou pelo github. Tente utilizando 'Q' como periodicidade.

Utilizando o seu exemplo:
consumo_sa = series_ipeadata(1198638884, periodicity = 'Q')
